language: php

php:
  - 5.5
  - 5.6

services:
  - postgres
  - rabbitmq

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travisci_hodor;' -U postgres
  - cp config/dist/config.travis.php config/config.test.php

install:
  - composer install

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/log/coverage.xml
